name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_eb413efe-62f1-4959-bc3e-7d27be467958 }}
          GH_TOKEN: ${{ secrets.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 }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          LOCALE: "en"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SYMBOL_VERSION: "3"
          
          
